# Generated by Django 4.1.7 on 2023-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Self Improvement'), (2, 'Biography'), (3, 'Economy'), (4, 'Fiction'), (5, 'Science'), (6, 'Mindset'), (7, 'Other')]),
        ),
    ]
